from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
PROJECT_DIR = BASE_DIR.parent

TILE_SIZE = 64
BOARD_PADDING = 32
SIDEBAR_WIDTH = 300
FPS = 60
MIN_WINDOW_HEIGHT = 660

ASSET_DIR = BASE_DIR / "assets"
IMAGE_DIR = ASSET_DIR / "images"
FONT_DIR = ASSET_DIR / "fonts"
LEVEL_DIR = PROJECT_DIR / "data"
SOLVER_DIR = PROJECT_DIR / "solver"
SOLVER_BIN_DIR = BASE_DIR / "bin"
CPP_SOLVER_EXE = SOLVER_BIN_DIR / "cpp_solver.exe"
CPP_SOLVER_BUILD_STAMP = SOLVER_BIN_DIR / "cpp_solver.build"
SOLVER_TIMEOUT_SECONDS = 130

FONT_REGULAR = FONT_DIR / "font_regular.ttf"
FONT_BOLD = FONT_DIR / "font_bold.ttf"

IMAGE_PLAYER = IMAGE_DIR / "player.png"
IMAGE_TARGET = IMAGE_DIR / "target.png"
IMAGE_BOX = IMAGE_DIR / "box.png"
IMAGE_WALL = IMAGE_DIR / "wall.png"
IMAGE_GROUND = IMAGE_DIR / "ground.png"

COLOR_BG = (20, 23, 27)
COLOR_BOARD_BG = (31, 36, 42)
COLOR_BOARD_BORDER = (72, 84, 98)
COLOR_SIDEBAR = (35, 41, 49)
COLOR_PANEL_LINE = (79, 92, 108)
COLOR_TEXT = (245, 247, 250)
COLOR_MUTED = (174, 184, 198)
COLOR_BUTTON = (70, 86, 105)
COLOR_BUTTON_HOVER = (93, 114, 138)
COLOR_BUTTON_TEXT = (250, 252, 255)
COLOR_BUTTON_BORDER = (128, 145, 166)
COLOR_WIN_OVERLAY = (0, 0, 0, 150)
